### ISSUE TITLE
Improvement Request: update some endpoints to newest scope

### ISSUE THREAD

**Issue by theca11** [twurple/twurple#323]
Last February, 3 API endpoints were updated to use the `channel:manage:broadcast` scope. Even though the old `user:edit:broadcast` is still valid, it may be a good idea to add the new scope too, as it's indeed usable and the official Twitch docs refer exclusively to it (and so it may be confusing for some users expecting it to work)

For reference, extracted from [Twitch Changelog](https://dev.twitch.tv/docs/change-log) (2021-02-26):

> The following endpoints were updated to use the channel:manage:broadcast scope. The previous scope remains valid.
> 
> Modify Channel Information
> Create Stream Marker
> Replace Stream Tags

**Comment by d-fischer** [comment]
This is a breaking change and could only be made available using a configuration option, probably on the methods themselves, defaulting to the old scope.
That default could then be changed in the next **major** version, to adhere to SemVer properly.

**Comment by theca11** [comment]
Better late than never :D It's a pity we missed the 5.0 release for this change
Still not a super important thing since the old scope is valid, but I guess it will be deprecated at some point

**Comment by TheOct0** [comment]
May I try my hand at making this change via a PR?
I'm trying to become more active as a developer outside my own projects, and I feel this could be a good first pull request for this.
I believe the best way to go at this would be to make it an option when creating a new `ApiClient`. We could make it so that, if a certain argument is passed when using the constructor, all the subsequent method calls from this object would use the new scope, instead of the old one.
