### ISSUE TITLE
Retry requests failing with network or server errors

### ISSUE THREAD

**Issue by Ionys320** [twurple/twurple#400]
## Feature Request

Hi! Is there a way to implement [retry-as-promised](https://www.npmjs.com/package/retry-as-promised) or an equivalent into twurple-api? To give a usage example, I often have FetchError with the message `connect ETIMEDOUT 199.232.82.214:443` (after seeing with a Twitch moderator, it would be linked to a problem with Twitch load balancing), and retry the request one or two times could solve this kind of issue.

**Comment by msikma** [comment]
Would definitely be nice to have something that is able to handle common temporary errors. I've not quite run into this issue with Twurple yet but in my experience with the Discord API it's kind of tricky to know how to handle all temporary errors that can occur because you usually don't know to account for them until they happen.

You basically end up writing what amounts to boilerplate code that wraps around the API calls and checks for timeouts and things like that. I feel like in 99% of projects you just want those cases to be handled automatically, possibly with a `retry: false` type option.
