### ISSUE TITLE
[Api] Export `HelixCustomRewardData` so it can be used outside of lib.

### ISSUE THREAD

**Issue by Satont** [twurple/twurple#436]
## Feature Request

Please re-export `HelixCustomRewardData` from `@twurple/api`

**Comment by d-fischer** [comment]
What is the use case for this? It's only used internally for the custom reward fetch.

**Comment by Satont** [comment]
I'm respond from backend to frontend with list of rewards, without export i should write typings manually.

**Comment by d-fischer** [comment]
Then you really *should* write your own types. Don't couple your own backend responses to API implementation details.

**Comment by Satont** [comment]
> Then you really _should_ write your own types. Don't couple your own backend responses to API implementation details.

I just respond with twitch rewards without modify data. Why i should retype whole that things if i can just return what api returns?

**Comment by d-fischer** [comment]
> I just respond with twitch rewards without modify data. Why i should retype whole that things if i can just return what api returns?

Because your frontend will break if the response type changes.



> Why other raw types exists then and available for import?

In most cases this is because it's internally used by other twurple packages. In some cases it might be that it *was* used for that before, but is now still left as an export because I forgot to remove it. Could also be a plain mistake. Either way, all of these should be marked as `@private` via JSDoc and you should exclusively use the types listed in the [reference](https://twurple.js.org/reference/api/).

**Comment by Satont** [comment]
> Because your frontend will break if the response type changes.

Then my backend and twurple will be also break if twitch change something in api response. I do not get your point.
While frontend `@twurple/api` and backend `@twurple/api` has same version it should act the same.

**Comment by d-fischer** [comment]
Yes, Twurple can break if Twitch changes something, but it can also then fix that break without an external interface change and you just need to update it. If you rely on the raw data directly, you definitely have to do your own fix.

This is the whole point of the API wrappers. If you do raw data, might as well just not use them.
