### ISSUE TITLE
chat: dynamically switch betwen message rate limiters

### ISSUE THREAD

**Issue by StimulCross** [twurple/twurple#443]
## Feature Request

In the current implementation, we can pass the `isAlwaysMod` option to use higher limits. But if at some point the bot loses mod status on any channel, there is a real risk of being banned for 30 minutes.

I propose a feature to dynamically switch between rate limiters. If at some point I'm no longer sure that my bot is a moderator on all channels, I can switch to the regular rate limiter so as not to get banned. And then switch back when I'm sure that the bot is mod on all channels.

**Comment by d-fischer** [comment]
The property to assume that your bot is always a mod is a strong requirement that you have to communicate to your users. If you notice that your bot is not a mod anymore in any channel, and you are using `isAlwaysMod`, the safest course of action is to stop sending any messages to that channel until the mod status is reinstated. (I'm pretty sure that's what Nightbot does.)

Also, imagine what kind of implication this would have on users of your bot who actually do keep up the mod status. Latency will build up quite quickly as messages try to go out faster than they actually can - and there's nothing they can do about it, because some random other user of your bot is at fault.

Additionally, this is technically probably impossible, as with `isAlwaysMod` a completely different rate limiter class is used, which can not easily share state with the non-mod one, as the non-mod version is partitioned by channel.
