### ISSUE TITLE
Support for additional EventSub subscription types

### ISSUE THREAD

**Issue by jadamhall** [twurple/twurple#535]
## Feature Request

Twitch has implemented additional EventSub subscription types:

- [channel.chat.clear](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatclear)
- [channel.chat.clear_user_messages](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatclear_user_messages)
- [channel.chat.message_delete](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatmessage_delete)
- [channel.chat.notification](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatnotification)

**Comment by ccKep** [comment]
@d-fischer the PR only **partially** solved this issue.

The arguably most important new subscription in this issue (channel chat notification) was not added in there. This event contains info on multi-month gifts, prime-paid-upgrades etc.

Please don't get me wrong, I'm not demanding it to be added (I would support the effort of implementing it if I could).
I just don't see this issue completed in that regard (unless there is another issue solely for channel chat notification that I'm missing).

Thanks for the great work so far (also special thanks to @zunderscore)

**Comment by ccKep** [comment]
I went ahead and created some interfaces as a starting point, however I'm pretty sure that's not the way code should be structured in twurple.

If anyone wants to take this as a starting point to copy/paste instead of having to write it all out again: Feel free.

https://github.com/ccKep/twurple/commit/c1860cab51b6bf710b029fe4a6322b48862f277c
