### ISSUE TITLE
webhook_callback_verification

### ISSUE THREAD

**Issue by Digital39999** [twurple/twurple#539]
## Bug Report

![image](https://github.com/twurple/twurple/assets/65065580/fd92aa5a-0496-42f9-be54-488a8f11f5bd)

### Code
![image](https://github.com/twurple/twurple/assets/65065580/87817393-e851-4b50-954a-2ee51d7f5c39)
![image](https://github.com/twurple/twurple/assets/65065580/01eed867-c461-426f-be79-b1f7f9f311c4)
![image](https://github.com/twurple/twurple/assets/65065580/0468c9f6-8926-4b3e-b20d-bab6041dfad5)

### Environment

- Version: 7.0.7
- Node version: 20.3.0
- Operating system: Docker?

**Comment by d-fischer** [comment]
Are you running multiple instances behind a load balancer? Because that scenario is not currently supported and will cause messages like this to occur, because the load balancer is likely to just send Twitch's requests to the wrong instance.

Otherwise, it should be noted that you need to run `onStreamOnline` and `onStreamOffline` for all your users on every start, or the listener may not recognize the requests coming in.

**Comment by Digital39999** [comment]
Not really, only thing i do is run 2 different instances, but they each use their own different domain.

**Comment by d-fischer** [comment]
Then please show more code. It would be great if you'd just put it in a code block rather than posting screenshots.

**Comment by Digital39999** [comment]
Was fixed, but check discord server for not receiving events issue.
